# Contig FASTA file
contig_fasta: data/contigs.fa

# Read metadata
read_metadata: read_metadata.tsv

# How many rounds of polishing that should be performed
iterations: 2

# Splitting
splitting:
    # Size of chunks in bytes
    chunk-size: 100000000

# Cluster configuration
cluster:
    # Cookiecutter parameters
    cookiecutter:
        url: https://github.com/Snakemake-Profiles/slurm
        profile_name: rackham_slurm
        cluster_config: cluster/slurm.yaml
        advanced_argument_conversion: false

    # Default Snakemake parameters
    snakemake:
        use-conda: true
        use-envmodules: true
        restart-times: 0
        jobs: 3000
        latency-wait: 120
