# Contig FASTA file
contig_fasta: data/contigs.fa

# Read metadata
read_metadata: read_metadata.tsv

# How many rounds of polishing that should be performed
iterations: 2

# Splitting
splitting:
    # Size of chunks in bytes
    chunk-size: 100000000

# Cluster configuration
cluster:
    cookiecutter_url: https://github.com/Snakemake-Profiles/slurm
    profile_name: test_slurm
    use-conda: true
    use-envmodules: true
    restart-times: 0
    jobs: 100
    latency-wait: 120

    # Parameters specific for the cookiecutter template
    account: test_slurm
    output: "logs/slurm-%j.out"
    error: "logs/slurm-%j.err"
    partition: core
    submit_script: slurm-submit-advanced.py
