$schema: "http://json-schema.org/draft-07/schema#"
description: config dictionary
type: object
properties:
    contig_fasta:
        type: string
        description: path to FASTA file with assembled contigs
    long_reads:
        type: array
        items:
            type: string
        description: directories where long read data is located
    short_reads:
        type: array
        items:
            type: string
        description: directories wehre short read data is located

required:
    - contig_fasta
    - long_reads

